server:
  port: 8081

spring:
  application:
    name: fraud

  datasource:
    url: jdbc:postgresql://localhost:5434/fraud
    username: raghav
    password: raghav

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: Asia/Kolkata
    hibernate:
      ddl-auto: update
    show-sql: true
